### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '__context__'

### ISSUE THREAD

**Issue by pycckuu** [socketubs/Sublimall#80]
Hi, I am receiving this error:

```
Error while creating archive

=================================== Traceback ===================================
Traceback (most recent call last):
  File "sublimall.commands.upload_command in /Users/MarkelovIgor/Library/Application Support/Sublime Text 3/Installed Packages/Sublimall.sublime-package", line 51, in pack_and_send
  File "sublimall.commands.upload_command in /Users/MarkelovIgor/Library/Application Support/Sublime Text 3/Installed Packages/Sublimall.sublime-package", line 208, in send_to_api
  File "sublimall.logger in /Users/MarkelovIgor/Library/Application Support/Sublime Text 3/Installed Packages/Sublimall.sublime-package", line 70, in show_report
  File "./traceback.py", line 270, in format_exc
  File "./traceback.py", line 181, in format_exception
  File "./traceback.py", line 122, in _iter_chain
AttributeError: 'NoneType' object has no attribute '__context__'
=================================================================================


SublimeText version: 3065
7za path: /usr/local/Cellar/p7zip/9.20.1/bin/7za
Sublimall version: 0.0.23
Operating System: Darwin-14.0.0-x86_64-i386-64bit
```

**Comment by Natim** [comment]
This is because you are trying to pass an exception that was not raised to traceback.
Try to do something like:

```
try:
    raise ReportError()
except ReportError as e:
    traceback.format_exc(e)
```
